"use client";

import jsPDF from "jspdf";

interface CandidateReportData {
    name: string;
    email?: string;
    phone?: string;
    finalScore: number;
    recommendation: string;
    atsScore: number;
    githubScore: number;
    proofScore: number;
    qualityScore: number;
    matchedSkills: string[];
    missingSkills: string[];
    explanation: string;
    githubProof?: string[];
    processedAt?: string;
}

export async function generateCandidateReport(data: CandidateReportData): Promise<void> {
    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.getWidth();
    let y = 20;

    // Helper functions
    const centerText = (text: string, yPos: number, fontSize: number = 12) => {
        pdf.setFontSize(fontSize);
        const textWidth = pdf.getTextWidth(text);
        pdf.text(text, (pageWidth - textWidth) / 2, yPos);
    };

    const addSection = (title: string) => {
        y += 10;
        pdf.setFontSize(12);
        pdf.setTextColor(99, 102, 241); // Primary color
        pdf.text(title, 20, y);
        pdf.setTextColor(0, 0, 0);
        y += 2;
        pdf.setDrawColor(99, 102, 241);
        pdf.line(20, y, pageWidth - 20, y);
        y += 8;
    };

    // Header
    pdf.setFontSize(24);
    pdf.setTextColor(99, 102, 241);
    centerText("SkillSnap AI", y, 24);
    y += 8;
    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    centerText("Candidate Analysis Report", y, 10);
    y += 15;

    // Candidate Info
    pdf.setFontSize(18);
    pdf.setTextColor(0, 0, 0);
    pdf.text(data.name || "Unknown Candidate", 20, y);
    y += 6;

    if (data.email) {
        pdf.setFontSize(10);
        pdf.setTextColor(100, 100, 100);
        pdf.text(data.email, 20, y);
        y += 5;
    }

    if (data.phone) {
        pdf.text(data.phone, 20, y);
        y += 5;
    }

    // Score Box
    y += 5;
    const scoreColor = data.finalScore >= 80 ? [34, 197, 94] :
        data.finalScore >= 60 ? [59, 130, 246] :
            data.finalScore >= 40 ? [245, 158, 11] : [239, 68, 68];

    pdf.setFillColor(scoreColor[0], scoreColor[1], scoreColor[2]);
    pdf.roundedRect(pageWidth - 70, y - 25, 50, 30, 3, 3, "F");
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(24);
    pdf.text(String(data.finalScore), pageWidth - 52, y - 8);
    pdf.setFontSize(8);
    pdf.text("SCORE", pageWidth - 52, y);

    // Recommendation
    y += 15;
    pdf.setTextColor(0, 0, 0);
    pdf.setFontSize(14);
    pdf.text(`Recommendation: ${data.recommendation}`, 20, y);

    // Score Breakdown
    addSection("Score Breakdown");
    pdf.setFontSize(10);

    const scores = [
        { label: "ATS Match", value: data.atsScore },
        { label: "GitHub Score", value: data.githubScore },
        { label: "Proof Score", value: data.proofScore },
        { label: "Quality Score", value: data.qualityScore },
    ];

    scores.forEach((score) => {
        pdf.text(`${score.label}:`, 25, y);
        pdf.text(`${score.value}%`, 80, y);

        // Progress bar
        pdf.setFillColor(230, 230, 230);
        pdf.rect(100, y - 3, 80, 4, "F");

        const barColor = score.value >= 70 ? [34, 197, 94] :
            score.value >= 50 ? [59, 130, 246] : [245, 158, 11];
        pdf.setFillColor(barColor[0], barColor[1], barColor[2]);
        pdf.rect(100, y - 3, (score.value / 100) * 80, 4, "F");

        y += 8;
    });

    // AI Analysis
    addSection("AI Analysis");
    pdf.setFontSize(10);
    const splitExplanation = pdf.splitTextToSize(data.explanation, pageWidth - 40);
    pdf.text(splitExplanation, 20, y);
    y += splitExplanation.length * 5 + 5;

    // Skills
    if (data.matchedSkills.length > 0) {
        addSection("Matched Skills");
        pdf.setFontSize(9);
        const skillsText = data.matchedSkills.join(" • ");
        const splitSkills = pdf.splitTextToSize(skillsText, pageWidth - 40);
        pdf.text(splitSkills, 20, y);
        y += splitSkills.length * 5 + 5;
    }

    if (data.missingSkills.length > 0) {
        addSection("Missing Skills");
        pdf.setFontSize(9);
        pdf.setTextColor(239, 68, 68);
        const missingText = data.missingSkills.join(" • ");
        const splitMissing = pdf.splitTextToSize(missingText, pageWidth - 40);
        pdf.text(splitMissing, 20, y);
        y += splitMissing.length * 5 + 5;
        pdf.setTextColor(0, 0, 0);
    }

    // GitHub Evidence
    if (data.githubProof && data.githubProof.length > 0) {
        addSection("GitHub Evidence");
        pdf.setFontSize(9);
        data.githubProof.forEach((proof) => {
            pdf.text(`✓ ${proof}`, 25, y);
            y += 5;
        });
    }

    // Footer
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    const footer = `Generated by SkillSnap AI • ${new Date().toLocaleDateString()}`;
    centerText(footer, pdf.internal.pageSize.getHeight() - 10, 8);

    // Save
    const fileName = `${data.name?.replace(/\s+/g, "_") || "candidate"}_report.pdf`;
    pdf.save(fileName);
}
